services:
  app:
    image: ghcr.io/cengizozel/oldenbyte:latest
    ports:
      - "3847:3000"
    restart: unless-stopped
    environment:
      - DATABASE_URL=file:/app/data/db.sqlite
      - UPLOADS_DIR=/app/data/uploads
    volumes:
      - ./data:/app/data

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json:ro
    command: --interval 300 oldenbyte-app-1
    restart: unless-stopped
